### ISSUE TITLE
Layer disappers

### ISSUE THREAD

**Issue by dbpatni** [3nids/quickfinder#24] opened 2014-11-19 08:43 UTC
Hi,

I am able to search in remote areas and correctly displayed but when I do a project search it returns a valid object in the layer.

But other objects in the same layer and other layers are not visible.

Thanks 

Deepak Patni

**Comment by spaceof7** [comment] 2015-05-14 23:56
I think I had the same problem which was caused by the layer CRS not matching the project CRS.  It looks like the plugin finds the coordinates of the object in the layer's CRS and zooms to those coordinates without checking to make sure the project CRS is the same.  If you set the project CRS to match that of the layer then that might solve your problem.

**Comment by 3nids** [comment] 2015-07-07 14:16
fixed in 3.2.8

**Closed by 3nids** 2015-07-07 14:16 UTC
